apiVersion: v1
kind: ReplicationController
metadata:
  name: mylogin-rc
spec:
  replicas: 4
  selector:
     app: mylogin
     version: 2.6.1
  template:
    metadata:
       labels:
          app: mylogin
          version: 2.6.1
    spec:
      containers:
      - name: mylogin-container
        image: 8919246895/myjavaimage:1
        ports:
         - containerPort: 8080
